---
version: "2.0"

services:
  app:
    image: ubuntu:latest
    
    env:
#1.Private information section, do not share data from this section!Раздел часной информации, неделитесь даннмы из этого раздела!
#1.Раздел часной информации, неделитесь даннмы из этого раздела!
     - "my_root_password=" #Root password for ssh connection.Пароль root для подключения по ssh
     - "MONIKER=" #Node name. Имя ноды
     - "MNEMONIC=" #Seed phrase from the test wallet. Deed фраза от тестового кошелька
     - "LINK_KEY=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets.Ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
#==================================================================
#2.Section of variables for node operation.
#2.Раздел переменных для работы ноды.
     - "binary=celestia-appd"
     - "vers=v0.6.0"
     - "genesis=https://github.com/celestiaorg/networks/raw/master/mamaki/genesis.json"
     - "folder=.celestia-app"
     - "denom=utia"
     - "chain=mamaki"
     - "gitrep=https://github.com/celestiaorg/celestia-app"
     - "gitfold=celestia-app"
     - "link_peer=https://raw.githubusercontent.com/Dimokus88/Celestia/main/PEER"
     - "link_rpc=https://raw.githubusercontent.com/Dimokus88/Celestia/main/state_sync"
     - "SHIFT=2000"
     - "SNAP_RPC=http://rpc2.bonded.zone:21357"
     - "autodelegate=yes"
#====================================   
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ; apt-get upgrade -y ; apt-get install -y  curl ; curl -s  https://raw.githubusercontent.com/Dimokus88/universe/main/main.sh | bash ; sleep infinity'
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
        
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 3Gi
        storage:
          size: 30Gi
         
  placement:
    akash: 
      attributes:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
