---
version: "2.0"

services:
  app:
    image: dimokus88/celestia:0.0.5
    
    env:
#1.Private information section, do not share data from this section!Раздел часной информации, неделитесь данными из этого раздела!
     - "my_root_password=" # пароль root для подключения по ssh
     - "MONIKER=" #Имя ноды (Если нетрудно, укажите в имени ноды Akash, например:DimokusAkash). Node name (If it is not difficult, specify Akash in the node name, for example:DimokusAkash). 
     - "MNEMONIC=" # seed phrase from the Deweb wallet. seed фраза от кошелька Deweb.
     - "LINK_KEY=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets. ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
#==================================================================
#2.Section of variables for node operation.Раздел переменных для работы ноды.
     #- "SNAP_RPC=https://celestia-testnet-rpc.polkachu.com:443"
     - "genesis=https://github.com/celestiaorg/networks/raw/master/mamaki/genesis.json"
     - "link_peer=https://raw.githubusercontent.com/Dimokus88/Celestia/main/PEER"
     #- "link_rpc=https://raw.githubusercontent.com/Dimokus88/Celestia/main/state_sync"
     - "autodelegate=yes"
     - "SHIFT=2000"
     - "vers=v0.5.4"
     - "keep_recent=5"
     - "keep_every=2000"
     - "pruning_interval=50"
     - "snapshot_interval=2000"
 #======================================================================
     
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
                
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
    params:
      storage:
        data:
          mount: /root/.celestia-app/    
   
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 3Gi
        storage:
        - size: 5Gi
        - name: data
          size: 95Gi
          attributes:
            persistent: true
            class: beta2
        
        
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
